# coding:utf-8
import os

IS_DEBUG = True  # 是否测试环境

GAME_ID = 7  # 游戏ID

MAIN_VERSION = 1  # 主版本号
SUB_VERSION = 2  # 子版本号

SERVICE_GATE = 9999  # 网关服务
SERVICE_PUB_SUB = 9998  # 发布订阅服务
SERVICE_AGENT = 9997  # 机器人
SERVICE_WEB = 9996  # Web
SERVICE_SYSTEM = 1  # 系统服务
SERVICE_AUTH = 2  # 登录认证服务
SERVICE_MALL = 3  # 商城服务
SERVICE_CDPH = 8  # 常德跑胡
SERVICE_HZMJ = 10  # 红中麻将
SERVICE_CSMJ = 12  # 长沙麻将
SERVICE_CDDHD = 45  # 常德多红对
SERVICE_WMQ = 48  # 喂麻雀
SERVICE_QUICK_PDK = 49  # 快速跑得快
SERVICE_HANG_SHOU_PAO_HU = 59  # 汉寿跑胡

QUIT_NORMAL = 0
QUIT_DISMISS = 1
QUIT_KICK = 2
QUIT_GAME_OVER = 3
QUIT_TIME_OUT_KICK = 5

# 桌子的状态
# 注意顺序不可修改，否则影响游戏进程
T_IDLE = 0  # 空闲中
T_READY = 1  # 准备中
T_PLAYING = 2  # 游戏中
T_CHECK_OUT = 3  # 结算中

DISMISS_SECONDS = 60  # 解散房间的等待时间
HEART_BEAT_SECONDS = 8  # 玩家的心跳时间

REASON_SEND = 1  # 玩家转账
REASON_RECEIVE = 2  # 接收到转账
REASON_SYSTEM_ADD = 3  # 系统添加
REASON_SYSTEM_SUB = 4  # 系统减少
REASON_BIND_SUCCESS = 5  # 绑定成功
REASON_INVITE_SUCCESS = 6  # 邀请成功
REASON_RE_INVITE_SUCCESS = 7  # 二次邀请成功
REASON_CREATE_ROOM_SUCCESS = 8  # 第一次创建房间成功
REASON_CREATE_ROOM_SUB = 10  # 开房扣除
REASON_CREATE_ROOM_LA_JIAO_DOU_SUB = 11  # 开房扣除辣椒豆
REASON_LOTTERY = 15  # 抽奖赠送

REASON_CLUB_ADD = 25  # 俱乐部馆主增加
REASON_CLUB_SUB = 26  # 俱乐部馆主扣除
REASON_GAME_ADD = 27  # 游戏增加
REASON_GAME_SUB = 28  # 游戏扣除
REASON_GAME_LIMIT_SUB = 29  # 游戏抽成
REASON_GAME_MANAGE = 30  # 游戏抽成
REASON_REMAIN_GAME_MANAGE = 31  # 大赏零头。给群主

REASON_SCORE_GAME_ADD = 32  # 游戏积分增加
REASON_GAME_SCORE_BUY_ITEM = 33  # 购买积分物品
REASON_GAME_WINNER_SUB = 34  # 大赢家扣除
REASON_MANAGE_TRANSFER = 35  # 积分转移
REASON_REMAIN_OTHER_GAME_MANAGE = 36  # 群主预先抽出积分


MODIFY_FLOOR = 1
MODIFY_SUB_FLOOR = 2
DEL_FLOOR = 3
DEL_SUB_FLOOR = 4

PAY_TYPE_CREATOR = 0
PAY_TYPE_AA = 1
PAY_TYPE_WINNER = 2

DIAMOND_ROOM = 0
MATCH_ROOM = 1

PAY_DIAMOND = 1
PAY_YUAN_BAO = 2
PAY_ROOM_DIAMOND = 3
PAY_CLUB_SCORE = 4

BROAD_CAST_LOTTERY = 1  # 红包广播
AGENT_UPDATE = 8  # 红包广播

PUSH_MESSAGE_CLUB_ROOM_CHANGE = 1  # 推送俱乐部房间状态更改
PUSH_USER_APPLY_JOIN_CLUB = 2
PUSH_ADD_USER_TO_CLUB = 3
PUSH_PASS_USER_JOIN_CLUB = 4
PUSH_AUTO_ROOM_CHANGE = 5
PUSH_CLUB_CREATE_ROOM = 6
PUSH_USER_CHANGE_DOU = 9
PUSH_INVITE_PLAYER_JOIN = 11
PUSH_CLUB_DEL_ROOM = 12

CALC_DIAMOND_WITH_PLAYER_NUM = {
    SERVICE_QUICK_PDK,
    SERVICE_CDPH, SERVICE_CDDHD, SERVICE_CSMJ, SERVICE_HZMJ
}

CALC_DIAMOND_WITH_SPEC = []

# System Running Path.
BASE_PATH = os.path.dirname(os.path.realpath(__file__)) + '/../'

# 输出目录路径
OUTPUT_PATH = BASE_PATH + 'output/'

# 日志文件写入路径
LOG_PATH = OUTPUT_PATH + 'logs/'

# 日志文件名
GAME_LOG_FILE = "game.log"

if __name__ == "__main__":
    print(BASE_PATH, LOG_PATH)
